Add a oneliner markdown document to test Sphinx markdown generator

diff --git a/bin/git-mt-llvm-svn2git-map b/bin/git-mt-llvm-svn2git-map
--- a/bin/git-mt-llvm-svn2git-map
+++ b/bin/git-mt-llvm-svn2git-map
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-. "$(dirname "$0")"/helpers/init.sh
+. "$(dirname "$0")"/mt-helpers/init.sh
 helper mt_llvm_svn
 helper mt_llvm_svn2git
 helper bisect
 
-usage() { echo "usage: $(print_cmdname) <commit>"; }
-
-[ "$#" -ge 1 ] || error "missing <commit>"
-[ "$#" -eq 1 ] || error "too many positional args"
+usage() { echo "usage: git $COMMAND_FROM_GIT <commit>"; }
 
 # Make sure this has a rev.
 COMMIT=$(run --hide-errors git rev-parse "$1"^{commit}) ||
@@ -25,22 +22,41 @@ run grep -q "^    llvm-svn: $REV\$" ||
 mt_llvm_svn2git_init || exit 1
 
 # Check if this is mapped.
-if mt_llvm_svn2git $REV >/dev/null;  then
+is_mapped() { mt_llvm_svn2git "$1" >/dev/null ;}
+if is_mapped $REV; then
     log "$COMMIT is already mapped to r$REV"
     exit 0
 fi
 
+# This commit has no SVN revision.
+SKIP=afb1d31c54204b7f6c11e4f8815d203bcf9cffa3
+
 # Binary search for the first one not mapped.
 # TODO: add a testcase for r1.
-# TODO: add a testcase for MT_LLVM_SVN2GIT_SKIP
+# TODO: add a testcase for SKIP.
 log "Looking for the first unmapped commit..."
-NOT="$(bisect mt_llvm_svn2git_is_commit_mapped $COMMIT^)" || exit 1
+is_commit_mapped() {
+    local commit="$1"
+
+    # Clump skipped commits with their parents.
+    local rev
+    if [ "$commit" = $SKIP ]; then
+        rev=$(mt_llvm_svn $commit^) ||
+            error "unexpected missing SVN rev for $commit^"
+    elif [ -n "$commit" ]; then
+        rev=$(mt_llvm_svn $commit) ||
+            error "unexpected missing SVN rev for $commit"
+    fi
+
+    is_mapped $rev >/dev/null 2>&1
+}
+LOW=$(bisect is_commit_mapped $COMMIT^) || exit 1
 
 # Update all the refs.
 log "Mapping commits..."
 
 # TODO: add a testcase for searching exactly one commit.
-REVLIST_ARGS=( $COMMIT --not $NOT )
+REVLIST_ARGS=( $COMMIT --not $LOW )
 run git rev-list --reverse --format=raw "${REVLIST_ARGS[@]}" |
 mt_llvm_svn_impl --append-commit |
 mt_llvm_svn2git_insert "${REVLIST_ARGS[@]}"
