Fine-tune git-apple-llvm-mt-generate
- Strip output from setup.
- Add --no-setup for testing without pinging remotes.
- Add --dry-run for skipping main generation commands.
- Fix a couple of bugs.

I think mt-generate is correct now.  Whether it works is another
question, given that it's built on top of
mt-split2mono-translate-branch, which is not really tested.

diff --git a/libexec/apple-llvm/git-apple-llvm-mt-generate b/libexec/apple-llvm/git-apple-llvm-mt-generate
--- a/libexec/apple-llvm/git-apple-llvm-mt-generate
+++ b/libexec/apple-llvm/git-apple-llvm-mt-generate
@@ -5,10 +5,12 @@ export NONGIT_OK=1
 helper canonicalize_path
 
 usage() {
-    printf "%s\n"                                                           \
-        "usage: $(print_cmdname) [options] <downstream>"                    \
-        ""                                                                  \
-        "   --git-dir=<dir>   Git directory to use (default: $DEFAULT_GIT_DIR)"
+    printf "%s\n"                                                             \
+        "usage: $(print_cmdname) [options] <downstream>"                      \
+        ""                                                                    \
+        "   --git-dir=<dir> Git directory to use (default: $DEFAULT_GIT_DIR)" \
+        "   --[no-]setup    Set up <dir> and update remotes (default: on)"    \
+        "   --dry-run       Don't actually generate anything"
 }
 
 APPLE_LLVM_MT_CONFIG="$(
@@ -16,10 +18,11 @@ APPLE_LLVM_MT_CONFIG="$(
 print_repos() { cat "$MT_CONFIG" | awk '$1 == "repo" {print $2, $3}'; }
 
 mt_setup() {
-    log "setting up mt in $GIT_DIR"
-    log "           using $MT_CONFIG"
+    log "Setting up and syncing $GIT_DIR"
+    log "  (based on $MT_CONFIG)"
     [ -d "$GIT_DIR" ] ||
-        run git init --bare "$GIT_DIR"
+        run git init --bare "$GIT_DIR" ||
+        error "failed to initialize '$GIT_DIR'"
     print_repos | {
         local forks= sleepnext=0
         while read name url; do
@@ -30,17 +33,24 @@ mt_setup() {
 
             clone="$GIT_DIR"/clones/$name.git
             if [ -d "$clone" ]; then
-                run git --git-dir $clone remote update
+                run git --git-dir $clone remote update >/dev/null ||
+                    error "failed to update remote '$name'"
             else
-                run mkdir -p $(dirname $clone)
-                run git clone --mirror $url $clone
-                run git --git-dir "$GIT_DIR" remote add $name $PWD/$clone
+                {
+                    run mkdir -p $(dirname $clone) >/dev/null &&
+                    run git clone --mirror $url $clone >/dev/null &&
+                    run git --git-dir "$GIT_DIR" \
+                        remote add $name $PWD/$clone >/dev/null
+                } ||
+                    error "failed to mirror remote '$name'"
             fi &
             forks="$forks $!"
         done
         wait $forks
-    } &&
-    run git --git-dir "$GIT_DIR" fetch --no-tags --all
+    } && {
+        run git --git-dir "$GIT_DIR" fetch --no-tags --all >/dev/null ||
+        error "failed to sync '$GIT_DIR'"
+    }
 }
 
 has_no_spaces() { [ "${1/ /}" = "$1" ]; }
@@ -60,18 +70,20 @@ mt_generate() {
         error "generate: invalid object '$object'"
 
     log "Generating $action from $object"
-    $generator "$object"
+    $generator "$object" || exit 1
 }
 
 mt_generate_mapping() {
     local remote=$1
-    local branches="$(git --git-dir "$GIT_DIR" show-ref |
+    local branches="$(git --git-dir "$GIT_DIR" show-ref | awk '{print $2}' |
     grep ^refs/remotes/$remote)"
 
     [ -n "$branches" ] || error "no branches found under '$remote'"
     local branch
     for branch in $branches; do
-        run git --git-dir "$GIT_DIR" apple-llvm mt llvm-svn2git-map $branch
+        run --dry git --git-dir "$GIT_DIR" \
+            apple-llvm mt llvm-svn2git-map $branch ||
+            error "failed to generate mapping for '$branch'"
     done
 }
 
@@ -104,27 +116,42 @@ mt_generate_branch() {
             error "generate $branch: invalid repeat ref '$ref'"
     fi
 
-    run git --git-dir "$GIT_DIR" apple-llvm mt split2mono-translate-branch \
-        ${repeat:+--repeat }$repeat $branch $refdirs
+    run --dry git --git-dir "$GIT_DIR"            \
+        apple-llvm mt split2mono-translate-branch \
+        ${repeat:+--repeat }$repeat $branch $refdirs ||
+        error "failed to generate branch '$branch'"
 }
 
 DEFAULT_GIT_DIR=mt-repo.git
 GIT_DIR=$DEFAULT_GIT_DIR
-if [ "${1%%=*}" = "--git-dir" ]; then
-    parse_cmdline_option --git-dir GIT_DIR "$@"
-    shift $?
-    [ -n "$GIT_DIR" ] || error "--git-dir cannot be empty"
-fi
+SETUP=1
+NAME=
+while [ $# -gt 0 ]; do
+    case "$1" in
+        --git-dir|--git-dir=*)
+            parse_cmdline_option --git-dir GIT_DIR "$@"
+            shift $?
+            [ -n "$GIT_DIR" ] || error "--git-dir cannot be empty"
+            ;;
+        --dry-run)  DRY_RUN=1; shift ;;
+        --setup)    SETUP=1; shift ;;
+        --no-setup) SETUP=0; shift ;;
+        --help|--usage|-h) usage; exit 0 ;;
+        -*) error "unknown option '$1'" ;;
+        *)
+            [ -z "$NAME" ] || error "too many positional arguments"
+            [ -n "$1" ] || error "empty name for downstream"
+            has_no_spaces "$1" || error "branch name '$1' has spaces"
+            NAME=$1
+            MT_CONFIG="$APPLE_LLVM_MT_CONFIG/$NAME.mt-config"
+            [ -f "$MT_CONFIG" ] ||
+                error "config for '$NAME' not found at '$MT_CONFIG'"
+            shift
+            ;;
+    esac
+done
 
-[ $# -ge 1 ] || error "missing mt-config name"
-[ $# -le 1 ] || error "too many positional arguments"
-
-NAME="$1"
-MT_CONFIG="$APPLE_LLVM_MT_CONFIG/$NAME.mt-config"
-[ -f "$MT_CONFIG" ] ||
-    error "config for '$NAME' not found at '$MT_CONFIG'"
-
-#mt_setup
+[ $SETUP -eq 0 ] || mt_setup || exit 1
 cat "$MT_CONFIG" | sort | awk '$1 == "generate" {print $3, $4}' |
 while read action object; do
     mt_generate "$action" "$object" ||
