mt-generate: Implement tag creation
`generate tag` is the first step in implement tags.  It's just like
translating a branch, except tags are abandoned and not updated again.

Note that this commit exposes tags from the remotes:

- The monorepo destination tags are synced and stored at `refs/tags/*`,
  as if by `--tags` on every fetch.  This is the usual tagging model.
- Other remotes' tags will surely conflict.  I've chosen a somewhat
  arbitrary refspec of `+refs/tags/*:refs/remotes/$remote/*/tag`.  This
  avoids local collisions.

This commit is poorly tested so far.

This feature is also groundwork for `generate tags`, which will allow
pattern matching of some sort to import existing tags from split
directories en masse.  Likely coming soon...

diff --git a/libexec/apple-llvm/git-apple-llvm-mt-generate b/libexec/apple-llvm/git-apple-llvm-mt-generate
--- a/libexec/apple-llvm/git-apple-llvm-mt-generate
+++ b/libexec/apple-llvm/git-apple-llvm-mt-generate
@@ -17,13 +17,13 @@ usage() {
         "   --[no-]verbose  Use verbose output (default: \$VERBOSE)"          \
         "   --[no-]setup    Set up and update remotes (default: on)"          \
         "   --[no-]clean    Clean local progress (default: off, for now)"     \
-        "   --[no-]generate Generate branches (default: on)"                  \
+        "   --[no-]generate Generate branches/tags/etc. (default: on)"        \
         "   --[no-]push     Push to the destination(s) (default: on)"         \
         "   --push-only     Only push previous results"                       \
         "   --dry-run       Don't actually generate anything, just debug"     \
         "                   commands that would run"                          \
         "   --check-for-work"                                                 \
-        "                   Print the first <branch> that needs work, but"    \
+        "                   Print the first piece of work to do, but"         \
         "                   don't actually do anything"                       \
         "   --sync-destinations"                                              \
         "                   Sync destinations repeatedly until there is no"   \
@@ -45,15 +45,16 @@ usage() {
         "                   List generate actions, including upstream"        \
         "   --list-repos    List repos (and exit)"                            \
         "   --list-branches List branches to generate (and exit)"             \
-        "   --list-merged-branches"                                           \
-        "                   List branches to generate, including upstream"    \
+        "   --list-tags     List tags to generate (and exit)"                 \
+        "   --list-merged-(tags|branches)"                                    \
+        "                   List along with upstream mt-configs (and exit)"   \
         "   --list-dirs     List declared dirs (and exit)"                    \
-        "   --list-(active|inactive|repeat)-dirs=<branch>"                    \
+        "   --list-(active|inactive|repeat)-dirs=(<branch>|<tag>)"            \
         "                   List active, inactive, or repeated dirs for"      \
-        "                   <branch> (and exit)"                              \
-        "   --list-(active|inactive|repeat|all)-refdirs=<branch>"             \
+        "                   <branch> or <tag> (and exit)"                     \
+        "   --list-(active|inactive|repeat|all)-refdirs=(<branch>|<tag>"      \
         "                   List active, inactive, repeated, or all dirs for" \
-        "                   <branch> in <ref>:<dir> format (and exit)"
+        "                   <branch> or <tag> in <ref>:<dir> format (and exit)"
 }
 
 DEFAULT_CONFIG_DIR="$(
@@ -82,11 +83,14 @@ print_actions_impl()   { cat "$1" | awk '$1 == "generate" {print $2, $3}'; }
 print_actions()        { print_actions_impl "$MT_CONFIG"; }
 print_merged_actions() { print_actions_impl "$MERGED_MT_CONFIG"; }
 print_repos() { cat "$MERGED_MT_CONFIG" | awk '$1 == "repo" {print $2, $3}'; }
-print_branches_impl() {
-    print_actions_impl "$1" | awk '$1 == "branch" {print $2}' | sort
+print_refs_impl() {
+    print_actions_impl "$2" | awk -v type="$1" '$1==type{print $2}' |
+    sort --version-sort
 }
-print_branches()        { print_branches_impl "$MT_CONFIG"; }
-print_merged_branches() { print_branches_impl "$MERGED_MT_CONFIG"; }
+print_branches()        { print_refs_impl branch "$MT_CONFIG"; }
+print_tags()            { print_refs_impl tag    "$MT_CONFIG"; }
+print_merged_branches() { print_refs_impl branch "$MERGED_MT_CONFIG"; }
+print_merged_tags()     { print_refs_impl tag    "$MERGED_MT_CONFIG"; }
 print_dirs() {
     cat "$MERGED_MT_CONFIG" | awk '$1 == "declare-dir" {print $2}' | sort
 }
@@ -266,21 +270,31 @@ mt_setup() {
         done
     } || return 1
 
+    # Compute the destination repos.
+    local splitdest monodest
+    splitdest="$(show_splitref_destination)" || exit 1
+    monodest="$(show_monorepo_destination)" || exit 1
+
     log "Combining object databases"
     print_repos |
     while read name url; do
         log "  - $name"
         # Ignore errors here, since often the remote will already exist.
         run --hide-errors git remote add $name $PWD/clones/$name.git >$gitout
-        run $hide git fetch -q --no-tags $name >$gitout ||
+        local remotetags
+        if [ "$name" = "$monodest" ]; then
+            remotetags="refs/tags/*"
+        else
+            remotetags="refs/remotes/$name/*/tag"
+        fi
+        run $hide git fetch -q $name                \
+            "+refs/heads/*:refs/remotes/$name/*"    \
+            "+refs/tags/*:$remotetags"              \
+            >$gitout ||
         error "failed to sync '$GIT_DIR'"
     done || return 1
 
     # Check that the destination repos work.
-    local splitdest monodest
-    splitdest="$(show_splitref_destination)" || exit 1
-    monodest="$(show_monorepo_destination)" || exit 1
-
     run git remote | run grep "$splitdest" >/dev/null ||
         error "splitref destination '$splitdest' is not a repo"
     run git remote | run grep "$monodest" >/dev/null ||
@@ -645,23 +659,53 @@ does_mtref_match_goal() {
     [ -z "$work" ]
 }
 
-mt_generate_branch() {
-    # Get the branch name and prepend refs/heads/.
-    local heads=refs/heads/
-    local rawbranch=$1
-    local branch_name=${rawbranch#$heads}
-    local branch=$heads$branch_name
+mt_ref_init_helper() {
+    # From parent: local rawtarget
+    # From parent: local refsprefix
+    # From parent: local target
+    # From parent: local mttype
+    # From parent: local mtname
+    # From parent: local mtprefix
+    case "$mttype" in
+        branch) refsprefix=refs/heads/ mtprefix=refs/heads/mt/     ;;
+        tag)    refsprefix=refs/tags/  mtprefix=refs/heads/mt-tag/ ;;
+        *) error "unsupported ref type to generate: '$mttype'"
+    esac
+    mtname="${rawtarget#$refsprefix}"
+    [ ! "${mtname:0:5}" = refs/ ] ||
+        error "unrecognized $1 scheme $rawtarget;" \
+              "expected <name> or $refsprefix<name>"
+    target=$refsprefix$mtname
+}
 
-    local refdirs repeat
-    refdirs="$(print_active_refdirs "$rawbranch")" ||
-        error "failed to extract active refdirs for $rawbranch"
-    repeat="$(print_repeat "$rawbranch")" ||
-        error "failed to extract any repeat directive for $rawbranch"
-    start="$(print_start "$rawbranch")" ||
-        error "failed to extract any start directive for $rawbranch"
+mt_generate_branch() { mt_generate_ref "$@"; }
+mt_generate_tag()    { mt_generate_ref "$@"; }
+mt_fetch_branch()    { mt_fetch_ref "$@"; }
+mt_fetch_tag()       { mt_fetch_ref "$@"; }
+mt_push_branch()     { mt_push_ref "$@"; }
+mt_push_tag()        { mt_push_ref "$@"; }
+
+mt_generate_ref() {
+    # From parent: local action
+    local mtname refsprefix mtprefix target rawtarget="$1" mttype="$action"
+    mt_ref_init_helper
+
+    if check_for_work && [ $mttype = tag ]; then
+        run --hide-errors git rev-parse --verify $target^{tag} ||
+            report_work $mttype "$mtname"
+        return 0;
+    fi
+
+    local refdirs repeat start
+    refdirs="$(print_active_refdirs "$rawtarget")" ||
+        error "failed to extract active refdirs for $rawtarget"
+    repeat="$(print_repeat "$rawtarget")" ||
+        error "failed to extract any repeat directive for $rawtarget"
+    start="$(print_start "$rawtarget")" ||
+        error "failed to extract any start directive for $rawtarget"
 
     [ -n "$refdirs" ] ||
-        error "generate $branch: no 'dir' declarations"
+        error "generate $target: no 'dir' declarations"
 
     local refdir ref dir dirs sha1
     local mtref mtsha1 work
@@ -671,17 +715,17 @@ mt_generate_branch() {
         dir=${refdir#*:}
         dirs="${dirs}${dirs:+ }$dir"
         [ "$refdir" = "$ref:$dir" ] ||
-            error "generate $branch: invalid 'dir' with colon '$refdir'"
+            error "generate $target: invalid 'dir' with colon '$refdir'"
         sha1=$(run --dry git rev-parse --verify $ref^{commit}) ||
-            error "generate $branch: invalid ref '$ref' in dir '$dir'"
+            error "generate $target: invalid ref '$ref' in dir '$dir'"
         goal_sha1s=( "${goal_sha1s[@]}" "$sha1" )
         [ "$dir" = "*" ] &&
-            error "generate $branch: invalid dir '$dir' for ref '$ref'"
+            error "generate $target: invalid dir '$dir' for ref '$ref'"
 
         # Figure out if there's work to do, if we haven't found it already.
         [ -z "$work" ] || continue
         # Caller: local mtsha1 work
-        mtref="mt/$branch_name/$dir/mt-split"
+        mtref="mt/$mtname/$dir/mt-split"
         mtsha1=$(run --hide-errors git rev-parse --verify $mtref^{commit})
         [ "$mtsha1" = "$sha1" ] || work=1
         mtsha1="${mtsha1:-$ZERO_SHA1}"
@@ -689,12 +733,12 @@ mt_generate_branch() {
         check_for_work || continue
 
         # If we found work just report it.
-        report_work branch "$branch_name: $dir"
+        report_work $mttype "$mtname: $dir"
         return 0
     done
 
-    refdirs="$(print_all_refdirs "$rawbranch")" ||
-        error "failed to extract complete refdirs for $rawbranch"
+    refdirs="$(print_all_refdirs "$rawtarget")" ||
+        error "failed to extract complete refdirs for $rawtarget"
 
     # Validate the start ref, regardless of whether we need it.
     [ -z "$start" ] ||
@@ -715,10 +759,9 @@ mt_generate_branch() {
         # "no-pass".  This command takes goal_sha1s implicitly and returns via
         # repeat_sha1.
         local repeat_sha1
-        [ "${repeat:0:${#heads}}" = $heads ] || repeat=$heads$repeat
         run mt_list_first_repeat_sha1 "$repeat"
 
-        mtref="mt/$branch_name/mt-repeat"
+        mtref="mt/$mtname/mt-repeat"
         mtsha1=$(run --hide-errors git rev-parse --verify $mtref^{commit})
         [ ! "$mtsha1" = "$repeat_sha1" ] || break
 
@@ -726,75 +769,89 @@ mt_generate_branch() {
         local changed
         changed="$(run mt_list_modified_top_level_paths \
             "$mtsha1" "$repeat_sha1" \
-            "$(print_repeat_dirs "$rawbranch")" "$(print_dirs)")"
+            "$(print_repeat_dirs "$rawtarget")" "$(print_dirs)")"
         [ -n "$changed" ] || break
 
         # There's work to do.
         work=1
         check_for_work || break
-        report_work branch "$branch_name: $changed"
+        report_work $mttype "$mtname: $changed"
         return 0
     done
 
     # Return early unless there's work to do.
     [ -n "$work" ] || return 0
 
-    refdirs="$(print_all_refdirs "$rawbranch")" ||
-        error "failed to extract complete refdirs for $rawbranch"
+    refdirs="$(print_all_refdirs "$rawtarget")" ||
+        error "failed to extract complete refdirs for $rawtarget"
 
-    run --dry git apple-llvm mt translate-branch $branch "$start" $refdirs ||
-        error "failed to generate branch '$branch'"
+    run --dry git apple-llvm mt translate-ref $target "$start" $refdirs ||
+        error "failed to generate $mttype '$target'"
 }
 
-mt_fetch_branch() {
-    local rawbranch="$1"
-    local branch="$rawbranch"
-    local heads=refs/heads/
-    [ "${branch:0:${#heads}}" = $heads ] || branch=$heads$branch
+mt_fetch_ref() {
+    # From parent: local action
+    local mtname refsprefix mtprefix target rawtarget="$1" mttype="$action"
+    mt_ref_init_helper
 
     # Fetch from local mirror.
     local monodest repeat
     monodest="$(show_monorepo_destination)" || exit 1
-    repeat="$(print_repeat "$rawbranch")" ||
-        error "failed to extract any repeat directive for $rawbranch"
-    mt_fetch_one_branch "$monodest" "$branch"
-    mt_fetch_one_branch "$monodest" "refs/heads/mt/$rawbranch/mt-repeat"
+    repeat="$(print_repeat "$rawtarget")" ||
+        error "failed to extract any repeat directive for $rawtarget"
+    mt_fetch_one_branch "$monodest" "$target"
+    [ $mttype = tag ] ||
+        mt_fetch_one_branch "$monodest" "$mtprefix$mtname/mt-repeat"
 
     local splitdest refdirs
     splitdest="$(show_splitref_destination)" || exit 1
-    refdirs="$(print_active_refdirs "$rawbranch")" || exit 1
+    refdirs="$(print_active_refdirs "$rawtarget")" || exit 1
     for refdir in $refdirs; do
         d=${refdir#*:}
-        mt_fetch_one_branch "$splitdest" "refs/heads/mt/$rawbranch/$d/mt-split"
+        mt_fetch_one_branch "$splitdest" "$mttarget$mtname/$d/mt-split"
     done
 
-    mt_fetch_splitrefs "$rawbranch"
+    mt_fetch_splitrefs "$rawtarget"
 }
 
 mt_fetch_splitrefs() {
-    local branch="$1"
+    # Maybe from parent: local mttype
+    local mtname refsprefix mtprefix target rawtarget="$1"
+    [ -n "$mttype" ] || local mttype=branch
+    mt_ref_init_helper
+
     local splitdest refdirs
-    refdirs="$(print_active_refdirs "$branch")" ||
-        error "failed to extract active refdirs for $branch"
+    refdirs="$(print_active_refdirs "$rawtarget")" ||
+        error "failed to extract active refdirs for $rawtarget"
     splitdest="$(show_splitref_destination)" || exit 1
     for refdir in $refdirs; do
         d=${refdir#*:}
-        mt_fetch_one_branch "$splitdest" "refs/heads/mt/$branch/$d/mt-split"
+        mt_fetch_one_branch "$splitdest" "$mtprefix$mtname/$d/mt-split"
     done
 }
 
 mt_fetch_one_branch() {
     local remote="$1"
-    local branch="$2"
+    local ref="$2"
 
-    local remote_ref="refs/remotes/$remote/${branch#refs/heads/}"
+    local remote_ref
+    if [ "${ref:0:10}" = refs/tags/ ]; then
+        remote_ref="refs/remote-tags/$remote/${ref#refs/tags/}^{tag}"
+    else
+        remote_ref="refs/remotes/$remote/${ref#refs/heads/}^{commit}"
+    fi
     local sha1
-    sha1="$(run --hide-errors git rev-parse "$remote_ref"^{commit})" || return 0
-    run --dry git update-ref "$branch" "$sha1" ||
-        error "failed to sync '$branch' from '$remote'"
+    sha1="$(run --hide-errors git rev-parse --verify "$remote_ref")" ||
+        return 0
+    run --dry git update-ref "$ref" "$sha1" ||
+        error "failed to sync '$ref' from '$remote'"
 }
 
-mt_push_branch() {
+mt_push_ref() {
+    # From parent: local mttype
+    local mtname refsprefix mtprefix target rawtarget="$1" mttype="$action"
+    mt_ref_init_helper
+
     local branch="$1"
     local old_mtdb_sha1=$MTDB_SHA1
     MTDB_SHA1=$(run git show-ref $MTDB_REF | awk '{print $1}')
@@ -807,34 +864,37 @@ mt_push_branch() {
     # there to the actual remote.
     local monodest repeat
     monodest="$(show_monorepo_destination)" || exit 1
-    repeat="$(print_repeat "$branch")" ||
-        error "failed to extract any repeat directive for $branch"
+    repeat="$(print_repeat "$rawtarget")" ||
+        error "failed to extract any repeat directive for $rawtarget"
     local repeatref
-    if [ -n "$repeat" ]; then
-        repeatref=refs/heads/mt/$branch/mt-repeat
+    if [ -n "$repeat" -a ! $mttype = tag ]; then
+        repeatref=$mtprefix$mtname/mt-repeat
         run --hide-errors git rev-parse --verify $repeatref^{commit} ||
             repeatref=
     fi
-    run --dry git push $monodest $MTDB_REF:$MTDB_REF $branch $repeatref \
+    run --dry git push $monodest $MTDB_REF:$MTDB_REF $target $repeatref \
         --force-with-lease=$MTDB_REF:$old_mtdb_sha1 ||
         error "failed to push $MTDB_REF to local $monodest"
     run --dry git -C clones/$monodest.git push --atomic origin \
-        $MTDB_REF:$MTDB_REF $branch $repeatref                 \
+        $MTDB_REF:$MTDB_REF $target $repeatref                 \
         --force-with-lease=$MTDB_REF:$old_mtdb_sha1 ||
-        error "failed to push $branch and $MTDB_REF to $monodest"
+        error "failed to push $rawtarget and $MTDB_REF to $monodest"
 
-    mt_push_splitrefs "$branch"
+    mt_push_splitrefs "$rawtarget"
 }
 
 mt_push_splitrefs() {
-    local branch="$1"
+    # Maybe from parent: local mttype
+    local mtname refsprefix mtprefix target rawtarget="$1"
+    [ -n "$mttype" ] || local mttype=branch
+    mt_ref_init_helper
 
     # Push the mt-split refs, which are only needed to optimize the next call.
     local splitdest refdir d ref refs refspec refspecs
     splitdest="$(show_splitref_destination)" || exit 1
-    for refdir in $(print_active_refdirs "$branch"); do
+    for refdir in $(print_active_refdirs "$rawtarget"); do
         d=${refdir#*:}
-        ref="refs/heads/mt/$branch/$d/mt-split"
+        ref="$mtprefix$mtname/$d/mt-split"
         run --hide-errors git rev-parse "$ref"^{commit} >/dev/null ||
             continue
         refs="$refs${refs:+ }$refs"
@@ -851,12 +911,12 @@ mt_push_splitrefs() {
 mt_generate_splitrefs() {
     # Get the branch name and prepend refs/heads/.
     local heads=refs/heads/
-    local rawbranch=$1
-    local branch=$rawbranch
+    local rawtarget=$1
+    local branch=$rawtarget
     [ "${branch:0:${#heads}}" = $heads ] || branch=$heads$branch
 
-    local refdirs="$(print_active_refdirs "$rawbranch")"
-    local repeat="$(print_repeat "$rawbranch")"
+    local refdirs="$(print_active_refdirs "$rawtarget")"
+    local repeat="$(print_repeat "$rawtarget")"
 
     [ -n "$refdirs" ] ||
         error "generate $branch: no 'dir' declarations"
diff --git a/libexec/apple-llvm/git-apple-llvm-mt-translate-ref b/libexec/apple-llvm/git-apple-llvm-mt-translate-ref
--- a/libexec/apple-llvm/git-apple-llvm-mt-translate-ref
+++ b/libexec/apple-llvm/git-apple-llvm-mt-translate-ref
@@ -7,10 +7,10 @@ helper mt_list_commits
 
 usage() {
     printf "%s\n" \
-        "usage: $(print_cmdname) [options] <branch> <start> <ref>:<dir>..." \
+        "usage: $(print_cmdname) [options] <target> <start> <ref>:<dir>..." \
         ""                                                                  \
-        "   <branch>      the branch to interleave"                         \
-        "   <start>       the start ref (ignored if <branch> exists)"       \
+        "   <target>      the ref to interleave"                            \
+        "   <start>       the start ref (ignored if <target> exists)"       \
         "                   this can safely be empty"                       \
         "   <ref>         a ref to interleave commits from"                 \
         "                   '%<ref>[{no-pass}]' to repeat commits"          \
@@ -22,19 +22,19 @@ usage() {
 }
 
 main() {
-    local branch start
+    local target start
     local -a refdirs
     parse_cmdline "$@" || return 1
 
     # Only initialize split2mono db if we will interleave commits.
     # Initializing the blob is not free and there's no point.
     mt_split2mono_init || return 1
-    translate_branch "$@" || return 1
+    translate_ref "$@" || return 1
     mt_split2mono_save || return 1
 }
 
 parse_cmdline() {
-    [ $# -ge 1 ] || usage_error "missing <branch>"
+    [ $# -ge 1 ] || usage_error "missing <target>"
     [ $# -ge 2 ] || usage_error "missing <start> (can be empty)"
     [ $# -ge 3 ] || usage_error "missing <ref>:<dir>..."
     local pos=0
@@ -45,7 +45,7 @@ parse_cmdline() {
                 exit 0
                 ;;
             *:*)
-                [ $pos -ne 0 ] || usage_error "invalid branch name '$1'"
+                [ $pos -ne 0 ] || usage_error "invalid target ref '$1'"
                 [ $pos -ne 1 ] || usage_error "invalid start ref '$1'"
                 refdirs=( "${refdirs[@]}" "$1" )
                 shift
@@ -56,24 +56,40 @@ parse_cmdline() {
             *)
                 [ $pos -lt 2 ] || usage_error "invalid <ref>:<dir> '$1'"
                 [ $pos -ne 1 ] || start="$1"
-                [ $pos -ne 0 ] || branch="$1"
+                [ $pos -ne 0 ] || target="$1"
                 pos=$(( $pos + 1 ))
                 shift
                 ;;
         esac
     done
-    [ -n "$branch" ] || usage_error "missing <branch>"
-    branch="${branch#refs/heads/}"
+    [ -n "$target" ] || usage_error "missing <target>"
+    [ "${target:0:5}" = "refs/" ] ||
+        usage_error "<target> must start with 'refs/'"
 
     [ ${#refdirs[@]} -gt 0 ] || usage_error "missing <ref>:<dir>"
 }
 
 is_translated() { mt_split2mono "$1" >/dev/null 2>/dev/null; }
-translate_branch() {
+translate_ref() {
     local current
-    current=$(run --hide-errors git rev-parse --verify \
-        refs/heads/$branch^{commit}) ||
+    current=$(run --hide-errors git rev-parse --verify $target^{commit}) ||
         current=$ZERO_SHA1
+
+    local mtprefix mtname mttype
+    if [ "${target:0:11}" = refs/heads/ ]; then
+        mttype=branch
+        mtname="${target#refs/heads/}"
+        mtprefix=refs/heads/mt/
+    elif [ "${target:0:10}" = refs/tags/ ]; then
+        mttype=tag
+        mtname="${target#refs/tags/}"
+        mtprefix=refs/heads/mt-tag/
+        [ "$current" = $ZERO_SHA1 ] ||
+            error "tag $target already exists at $current"
+    else
+        # For now we just handle tags and branches.
+        error "unsupported target '$target'; must be refs/{heads,tags}/"
+    fi
 
     local r d rd mtref sha1 goal_sha1 start_sha1
     local -a listdirs # refs to list commits of and for which directory
@@ -124,7 +140,7 @@ translate_branch() {
             goal_sha1s=( "${goal_sha1s[@]}" "$goal_sha1" )
         fi
 
-        mtref=refs/heads/mt/$branch/$suffix
+        mtref=$mtprefix$mtname/$suffix
         head_sha1=$(run --hide-errors \
             git rev-parse --verify $mtref^{commit}) ||
             head_sha1=$ZERO_SHA1
@@ -133,7 +149,7 @@ translate_branch() {
     done
 
     local head
-    head=$(run --hide-errors git rev-parse --verify $branch^{commit})
+    head=$(run --hide-errors git rev-parse --verify $target^{commit})
     if [ -z "$head" ]; then
         if [ -n "$start" ]; then
             head=$(run --dry git rev-parse --verify "$start"^{commit}) ||
@@ -200,8 +216,8 @@ process_new_commits() {
 
     local new_sha1dirs
     interleave_commits "${main_sha1dirs[*]}" "${goal_sha1dirs[*]}" ||
-        error "could not update branch"
-    update_refs "$branch" "$current" "${head_sha1dirs[*]}" || exit 1
+        error "could not update target '$target'"
+    update_refs "$current" "${head_sha1dirs[*]}" || exit 1
 }
 
 interleave_commits() {
@@ -211,7 +227,6 @@ interleave_commits() {
     # From parent: local -a head_sha1dirs
     # From parent: local -a other_sha1dirs
     # From parent: local -a goal_sha1dirs
-    local ref=refs/heads/${branch#refs/heads/}
     local result
     result="$(run "$split2mono" interleave-commits \
         "$MT_DB_SPLIT2MONO_DB" "$MT_DB_SVN2GIT_DB" \
@@ -224,51 +239,72 @@ interleave_commits() {
 }
 
 update_refs() {
+    # From parent: local target
     # From parent: local head
     # From parent: local new_sha1dirs
-    local branch="${1#refs/heads/}"
-    local current="$2"
-    local old_sha1dirs="$3"
+    local current="$1"
+    local old_sha1dirs="$2"
 
-    local ref=refs/heads/$branch
-    {
-        log "Updating $branch => $head"
-        run printf "update %s %s %s\n" $ref $head $current
-        local old_sha1 new_sha1 new_sd sd d
+    local -a updates
+    local sha1 sd d mtref update_error
+    if [ "$mttype" = tag ]; then
+        local -a message -a trailers
+        local dslash
+        message=( "Tagging $name" "" )
+        for sd in $new_sha1dirs; do
+            d=${sd#*:}
+            if [ "$d" = % ]; then
+                continue
+            elif [ "$d" = - ]; then
+                dslash=$d
+            else
+                dslash=$d/
+            fi
+
+            sha1=${sd%:*}
+            mtref=$mtprefix$mtname/$d/mt-split
+            updates=( "${updates[@]}" "update $mtref $sha1 $ZERO_SHA1" )
+            message=( "${message[@]}" "  - $sha1: $dslash" )
+            trailers=( "${trailers[@]}" "apple-llvm-split-dir: $dslash" )
+        done
+        message=( "${message[@]}" "" "${trailers[@]}" )
+        log "Tagging $mtname => $head"
+        printf "%s\n" "${message[@]}" | run git tag -a -F - $mtname $head ||
+            error "failed to tag '$mtname' as '$head'"
+        update_error="failed to update $refdirs for $mtname"
+    else
+        log "Updating $target => $head"
+        updates=( "update $target $head $current" )
+        local prev sha1 nsd sd d mtsuffix
         for sd in $old_sha1dirs; do
             d=${sd#*:}
-            old_sha1=${sd%:*}
-            new_sha1=
+            prev=${sd%:*}
+            sha1=
             if [ "$d" = % ]; then
-                ref=refs/heads/mt/$branch/mt-repeat
+                mtsuffix=/mt-repeat
             else
-                ref=refs/heads/mt/$branch/$d/mt-split
+                mtsuffix=/$d/mt-split
             fi
-            for new_sd in $new_sha1dirs; do
-                [ "$d" = "${new_sd#*:}" ] || continue
-                new_sha1=${new_sd%:*}
+            mtref=$mtprefix$mtname$mtsuffix
+            for nsd in $new_sha1dirs; do
+                [ "$d" = "${nsd#*:}" ] || continue
+                sha1=${nsd%:*}
                 break
             done
-            if [ -z "$new_sha1" ]; then
-                printf "poison update-ref\n"
-                error "missing output sha1 for '$d'"
-            fi
-            if [ $new_sha1 = $ZERO_SHA1 -a \
-                ! "$new_sha1" = "$old_sha1" ]; then
-                printf "poison update-ref\n"
-                error "internal: new value for $ref is $new_sha1" \
-                    "but it was $old_sha1"
-            fi
-            if [ "$new_sha1" = "$old_sha1" ]; then
-                log " - ${ref#refs/heads/} == $new_sha1"
-                run printf "verify %s %s\n" $ref $new_sha1
+            if [ "${sha1:-$ZERO_SHA1}" = $ZERO_SHA1 ]; then
+                error "missing sha1 for '$d' in $target => $head"
+            elif [ "$sha1" = "$prev" ]; then
+                updates=( "${updates[@]}" "verify $mtref $sha1" )
             else
-                log " - ${ref#refs/heads/} => $new_sha1"
-                run printf "update %s %s %s\n" $ref $new_sha1 $old_sha1
+                log " - $d: $prev => $sha1"
+                updates=( "${updates[@]}" "update $mtref $sha1 $prev" )
             fi
         done
-    } | run git update-ref --stdin ||
-        error "failed to update $branch and $refdirs"
+        update_error="failed to update $mtname and $refdirs"
+    fi
+
+    printf "%s\n" "${updates[@]}" | run git update-ref --stdin ||
+        error "$update_error"
 }
 
 main "$@"
