mt-generate: Take advantage of mt-splits for start refs

diff --git a/libexec/apple-llvm/git-apple-llvm-mt-generate b/libexec/apple-llvm/git-apple-llvm-mt-generate
--- a/libexec/apple-llvm/git-apple-llvm-mt-generate
+++ b/libexec/apple-llvm/git-apple-llvm-mt-generate
@@ -702,12 +702,12 @@ mt_generate_ref() {
     # For tags, return early if it already exists.
     [ -n "$work" -o ! $mttype = tag ] || return 0
 
-    local refdirs repeat start
+    local refdirs repeat rawstart
     refdirs="$(print_active_refdirs "$rawtarget")" ||
         error "failed to extract active refdirs for $rawtarget"
     repeat="$(print_repeat "$rawtarget")" ||
         error "failed to extract any repeat directive for $rawtarget"
-    start="$(print_start "$rawtarget")" ||
+    rawstart="$(print_start "$rawtarget")" ||
         error "failed to extract any start directive for $rawtarget"
 
     [ -n "$refdirs" ] ||
@@ -746,10 +746,13 @@ mt_generate_ref() {
     refdirs="$(print_all_refdirs "$rawtarget")" ||
         error "failed to extract complete refdirs for $rawtarget"
 
-    # Validate the start ref, regardless of whether we need it.
-    [ -z "$start" ] ||
-        run --dry git rev-parse --verify $start^{commit} >/dev/null ||
-        error "invalid start ref '$start'"
+    # Validate the start ref, regardless of whether we need it, and then
+    # canonicalize it.
+    [ -z "$rawstart" ] ||
+        run --dry git rev-parse --verify $rawstart^{commit} >/dev/null ||
+        error "invalid start ref '$rawstart'"
+    local start="$(run --dry git rev-parse --symbolic-full-name $rawstart)"
+    [ -n "$start" ] || start="$rawstart"
 
     # Use a loop so we can avoid nesting with "break".
     local handle_repeat_once=
diff --git a/libexec/apple-llvm/git-apple-llvm-mt-translate-ref b/libexec/apple-llvm/git-apple-llvm-mt-translate-ref
--- a/libexec/apple-llvm/git-apple-llvm-mt-translate-ref
+++ b/libexec/apple-llvm/git-apple-llvm-mt-translate-ref
@@ -69,11 +69,11 @@ parse_cmdline() {
     [ ${#refdirs[@]} -gt 0 ] || usage_error "missing <ref>:<dir>"
 }
 
+get_commit_sha1() { run --hide-errors git rev-parse --verify "$1"^{commit}; }
 is_translated() { mt_split2mono "$1" >/dev/null 2>/dev/null; }
 translate_ref() {
     local current
-    current=$(run --hide-errors git rev-parse --verify $target^{commit}) ||
-        current=$ZERO_SHA1
+    current=$(get_commit_sha1 $target) || current=$ZERO_SHA1
 
     local mtprefix mtname mttype
     if [ "${target:0:11}" = refs/heads/ ]; then
@@ -91,7 +91,19 @@ translate_ref() {
         error "unsupported target '$target'; must be refs/{heads,tags}/"
     fi
 
-    local r d rd mtref sha1 goal_sha1 start_sha1
+    # Try to get start sha1s from start commits.
+    local start_mtprefix start_mtname start_mttype
+    if [ "${start:0:11}" = refs/heads/ ]; then
+        start_mttype=branch
+        start_mtname="${start#refs/heads/}"
+        start_mtprefix=refs/heads/mt/
+    elif [ "${start:0:10}" = refs/tags/ ]; then
+        start_mttype=tag
+        start_mtname="${start#refs/tags/}"
+        start_mtprefix=refs/heads/mt-tag/
+    fi
+
+    local r d rd mtref goal_sha1
     local -a listdirs # refs to list commits of and for which directory
     local -a repeated # directories getting repeated
     local repeated_root # the root is getting repeated
@@ -133,26 +145,34 @@ translate_ref() {
         else
             # Figure out the goal sha1 for this directory.  Note that the
             # repeat goal is determined below.
-            goal_sha1=$(run --hide-errors \
-                git rev-parse --verify $r^{commit}) ||
+            goal_sha1=$(get_commit_sha1 $r) ||
                 error "failed to extract goal sha1 from '$r' for dir '$d'"
             goal_sha1dirs=( "${goal_sha1dirs[@]}" "$goal_sha1:$d" )
             goal_sha1s=( "${goal_sha1s[@]}" "$goal_sha1" )
         fi
 
+        # Set up the head.  If this is a 'dir' directive and there's no
+        # mt-split head yet, try finding one from the start directives.  That
+        # can fail if the branch/tag does not have this directory, or if it's
+        # not generated by this tool.  Last ditch, set to
+        # 0000000000000000000000000000000000000000.
         mtref=$mtprefix$mtname/$suffix
-        head_sha1=$(run --hide-errors \
-            git rev-parse --verify $mtref^{commit}) ||
-            head_sha1=$ZERO_SHA1
-
+        head_sha1=$(get_commit_sha1 $mtref)
+        if [ -z "$head_sha1" ]; then
+            if [ -n "$start_mtname" -a ! "$d" = "%" ]; then
+                mtref=$start_mtprefix$start_mtname/$suffix
+                head_sha1=$(get_commit_sha1 $mtref)
+            fi
+            [ -n "$head_sha1" ] || head_sha1=$ZERO_SHA1
+        fi
         head_sha1dirs=( "${head_sha1dirs[@]}" "$head_sha1:$d" )
     done
 
     local head
-    head=$(run --hide-errors git rev-parse --verify $target^{commit})
+    head=$(get_commit_sha1 $target)
     if [ -z "$head" ]; then
         if [ -n "$start" ]; then
-            head=$(run --dry git rev-parse --verify "$start"^{commit}) ||
+            head=$(get_commit_sha1 "$start") ||
                 error "failed to extract commit from start ref '$start'"
         else
             head=$ZERO_SHA1
