Flesh out the configuration story for git-apple-llvm-mt

diff --git a/bin/git-apple-llvm.d/git-apple-llvm-mt.d/git-apple-llvm-mt-setup b/bin/git-apple-llvm.d/git-apple-llvm-mt.d/git-apple-llvm-mt-setup
--- a/bin/git-apple-llvm.d/git-apple-llvm-mt.d/git-apple-llvm-mt-setup
+++ b/bin/git-apple-llvm.d/git-apple-llvm-mt.d/git-apple-llvm-mt-setup
@@ -1,18 +1,25 @@
 #!/bin/bash
 
+export NONGIT_OK=1
 . "$(dirname $0)"/../helpers/init.sh
+helper canonicalize_path
 
-APPLE_LLVM_MT_CONFIG="$APPLE_LLVM_BIN_DIR/../mt-config"
-print_repos() { find "$APPLE_LLVM_MT_CONFIG" -type f | xargs cat; }
-
-run() {
-    echo "$*" >&2
-    "$@" || exit 1
+usage() {
+    printf "%s\n"                                                           \
+        "usage: $(print_cmdname) [options] <downstream>"                    \
+        ""                                                                  \
+        "   --git-dir=<dir>   Git directory to use (default: $DEFAULT_GIT_DIR)"
 }
 
+APPLE_LLVM_MT_CONFIG="$(
+    relative_canonicalize_path "$APPLE_LLVM_BIN_DIR/../mt-config")"
+print_repos() { cat "$MT_CONFIG" | awk '$1 == "repo" {print $2, $3}'; }
+
 mt_setup() {
-    [ -d repo ] ||
-        run git init --bare repo
+    log "setting up mt in $GIT_DIR"
+    log "           using $MT_CONFIG"
+    [ -d "$GIT_DIR" ] ||
+        run git init --bare "$GIT_DIR"
     print_repos | {
         local forks= sleepnext=0
         while read name url; do
@@ -21,19 +28,35 @@ mt_setup() {
             [ -d "$clone" ]
             sleep_next=$?
 
-            clone=repo/clones/$name.git
+            clone="$GIT_DIR"/clones/$name.git
             if [ -d "$clone" ]; then
-                run git -C $clone remote update
+                run git --git-dir $clone remote update
             else
                 run mkdir -p $(dirname $clone)
                 run git clone --mirror $url $clone
-                run git -C repo remote add $name $PWD/$clone
+                run git --git-dir "$GIT_DIR" remote add $name $PWD/$clone
             fi &
             forks="$forks $!"
         done
         wait $forks
     } &&
-    run git -C repo fetch --no-tags --all
+    run git --git-dir "$GIT_DIR" fetch --no-tags --all
 }
+
+DEFAULT_GIT_DIR=mt-repo.git
+GIT_DIR=$DEFAULT_GIT_DIR
+if [ "${1%%=*}" = "--git-dir" ]; then
+    parse_cmdline_option --git-dir GIT_DIR "$@"
+    shift $?
+    [ -n "$GIT_DIR" ] || error "--git-dir cannot be empty"
+fi
+
+[ $# -ge 1 ] || error "missing mt-config name"
+[ $# -le 1 ] || error "too many positional arguments"
+
+NAME="$1"
+MT_CONFIG="$APPLE_LLVM_MT_CONFIG/$NAME.mt-config"
+[ -f "$MT_CONFIG" ] ||
+    error "config for '$NAME' not found at '$MT_CONFIG'"
 
 mt_setup
